services:
  # 测试环境服务
  h5-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: unibestx-h5:test
    container_name: unibestx-h5-test
    restart: always
    env_file:
      - deploy/.env.test
    ports:
      - "${H5_PROD_PORT:-8080}:80"

  # 生产环境服务
  h5-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: unibestx-h5:prod
    container_name: unibestx-h5-prod
    restart: always
    env_file:
      - deploy/.env.prod
    ports:
      - "${H5_PROD_PORT:-8080}:80"
