/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/src/pages/index/index" |
  "/src/pages/ai/ai" |
  "/src/pages/basic/basic" |
  "/src/pages/basic/components/Card" |
  "/src/pages/basic/components/EchartsDemoCard" |
  "/src/pages/basic/components/HttpDemoCard" |
  "/src/pages/basic/components/IconDemoCard" |
  "/src/pages/basic/components/LangSwitchCard" |
  "/src/pages/basic/components/RouterDemoCard" |
  "/src/pages/basic/components/SignatureCard" |
  "/src/pages/basic/components/SystemInfoDemoCard" |
  "/src/pages/basic/components/ThemeSwitchCard" |
  "/src/pages/basic/components/TimeDemoCard" |
  "/src/pages/basic/components/UViewUltraDemoCard" |
  "/src/pages/basic/components/ZPagingDemoCard" |
  "/src/pages/function/components/EnvCard" |
  "/src/pages/function/components/HapticsCard" |
  "/src/pages/function/components/MediaCard" |
  "/src/pages/function/components/SystemInfoCard" |
  "/src/pages/function/function" |
  "/src/pages/me/me";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/src/pages/index/index" | "/src/pages/basic/basic" | "/src/pages/function/function" | "/src/pages/me/me"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
