import { createI18n } from '@/uni_modules/lime-i18n';
import zhCN from './locales/zh-CN.json';
import enUS from './locales/en-US.json';
import { getDefaultLocale } from '@/src/utils/env/index.uts';

const i18n = createI18n({
  // 使用uni.getStorageSync('uVueI18nLocale') 能获取上次退出应用后保存的语言
  locale: getDefaultLocale(), // 默认显示语言
  fallbackLocale: 'en-US',
  messages: {
    'zh-CN': zhCN as UTSJSONObject,
    'en-US': enUS as UTSJSONObject
  } as UTSJSONObject
} as UTSJSONObject);

export default i18n;
