// #ifndef APP-ANDROID && !VUE3-VAPOR
import pinia from './vapor/index';
// #endif

// #ifdef APP-ANDROID && !VUE3-VAPOR
import pinia from './vdom/index.uts';
// #endif

export default pinia;

// #ifndef APP-ANDROID && !VUE3-VAPOR
export * from './vapor/app';
export * from './vapor/token';
export * from './vapor/user';
// #endif

// #ifdef APP-ANDROID && !VUE3-VAPOR
export * from './vdom/app.uts';
export * from './vdom/token.uts';
export * from './vdom/user.uts';
// #endif
