import { onMounted, onUnmounted } from 'vue';

const EVENT_PULL_DOWN_REFRESH = 'onPagePullDownRefresh';
const EVENT_STOP_PULL_DOWN_REFRESH = 'stopPagePullDownRefresh';

/**
 * 监听 NavBar 布局下拉刷新事件
 */
export function onNavbarPullDownRefresh(callback: () => void): void {
  onMounted(() => {
    uni.$on(EVENT_PULL_DOWN_REFRESH, callback);
  });
  onUnmounted(() => {
    uni.$off(EVENT_PULL_DOWN_REFRESH, callback);
  });
}

export const EVENT_SET_NAVBAR_TITLE = 'setNavbarTitle';
export const EVENT_RESET_NAVBAR_TITLE = 'resetNavbarTitle';

/**
 * 动态设置/修改 NavBar 布局及原生导航栏标题
 * @param title 新的导航栏标题文本
 */
export function setNavbarTitle(title: string): void {
  uni.$emit(EVENT_SET_NAVBAR_TITLE, title);
  uni.setNavigationBarTitle({
    title
  } as SetNavigationBarTitleOptions);
}

/**
 * 重置 NavBar 布局的导航栏标题为初始配置标题
 */
export function resetNavbarTitle(): void {
  uni.$emit(EVENT_RESET_NAVBAR_TITLE);
}

/**
 * 停止 NavBar 布局下拉刷新状态
 */
export function stopNavbarPullDownRefresh(): void {
  uni.$emit(EVENT_STOP_PULL_DOWN_REFRESH);
  uni.stopPullDownRefresh();
}

// 统一导出页面滚动与触底监听函数
export { onNavbarPageScroll, onNavbarReachBottom } from './pageScroll.uts';
