import { defineStore, PiniaStoreBase } from '@/uni_modules/x-pinia-s';
import type { IAppState } from '../types.uts';

const defaultAppState: IAppState = {
  mode: 'vdom'
};

/**
 * 应用底座基础状态 Store（纯底座上下文，与业务功能如主题、多语言完全解耦）
 */
export class AppStore extends PiniaStoreBase {
  state: IAppState = reactive<IAppState>({
    mode: 'vdom'
  });

  constructor() {
    super();
    this.bindState(this.state);
  }

  /**
   * 重置 Store 状态为初始默认值
   */
  override _doReset(): void {
    this.state.mode = defaultAppState.mode;
  }

  /**
   * 从本地缓存数据中反序列化还原 Store 状态
   */
  override _hydrate(data: UTSJSONObject): void {
    const _data = (data.state != null ? data.state : data) as UTSJSONObject;
    if (_data.mode != null) {
      this.state.mode = _data.mode as string;
    }
  }

  /**
   * 序列化 Store 状态用于持久化存储
   */
  override _serialize(): UTSJSONObject {
    return {
      mode: this.state.mode
    } as UTSJSONObject;
  }
}

export const useAppStore = defineStore<AppStore>('app', (): AppStore => new AppStore());
